import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, Table, TableRow, TableCell, BorderStyle, WidthType,
} from 'docx'

interface ExportData {
  brand: Record<string, unknown>
  strategy?: Record<string, unknown>
  calendar?: unknown[]
  assets?: Record<string, unknown>
  funnel?: Record<string, unknown>
  leads?: Record<string, unknown>
}

function heading(text: string, level: typeof HeadingLevel[keyof typeof HeadingLevel] = HeadingLevel.HEADING_1) {
  return new Paragraph({ text, heading: level, spacing: { before: 400, after: 200 } })
}

function body(text: string) {
  return new Paragraph({ children: [new TextRun({ text, size: 24 })], spacing: { after: 120 } })
}

function bullet(text: string) {
  return new Paragraph({
    children: [new TextRun({ text: `• ${text}`, size: 24 })],
    spacing: { after: 100 },
    indent: { left: 400 },
  })
}

function divider() {
  return new Paragraph({ text: '─'.repeat(60), spacing: { before: 200, after: 200 } })
}

export async function generateDocx(data: ExportData): Promise<Buffer> {
  const children: Paragraph[] = []

  // Title
  children.push(
    new Paragraph({
      children: [new TextRun({ text: 'Ooumph AI Marketing Plan', bold: true, size: 56, color: '6366f1' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `${data.brand.business_name as string} | Generated by Ooumph AI`, size: 28, color: '6b7280' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
    }),
    divider(),
  )

  // Strategy
  if (data.strategy) {
    const s = data.strategy as Record<string, unknown>
    children.push(
      heading('1. Marketing Strategy'),
      heading('Positioning', HeadingLevel.HEADING_2),
      body(s.positioning as string || ''),
      heading('Unique Value Proposition', HeadingLevel.HEADING_2),
      body(s.uniqueValueProposition as string || ''),
      heading('30-Day Objective', HeadingLevel.HEADING_2),
      body(s.thirtyDayObjective as string || ''),
    )

    if (s.contentPillars) {
      children.push(heading('Content Pillars', HeadingLevel.HEADING_2))
      for (const pillar of s.contentPillars as Array<{ name: string; description: string; topics: string[] }>) {
        children.push(
          new Paragraph({ children: [new TextRun({ text: pillar.name, bold: true, size: 24 })], spacing: { after: 80 } }),
          body(pillar.description),
          ...(pillar.topics || []).map((t) => bullet(t)),
        )
      }
    }
    children.push(divider())
  }

  // Assets
  if (data.assets) {
    const a = data.assets as Record<string, Record<string, unknown>>
    children.push(heading('2. Marketing Assets'))

    if (a.linkedInPost) {
      children.push(
        heading('LinkedIn Post', HeadingLevel.HEADING_2),
        body(a.linkedInPost.hook as string || ''),
        body(a.linkedInPost.body as string || ''),
        body(`CTA: ${a.linkedInPost.cta as string || ''}`),
      )
    }

    if (a.emailDraft) {
      children.push(
        heading('Email Draft', HeadingLevel.HEADING_2),
        body(`Subject: ${a.emailDraft.subject as string || ''}`),
        body(a.emailDraft.body as string || ''),
      )
    }

    if (a.adCopy) {
      children.push(
        heading('Ad Copy', HeadingLevel.HEADING_2),
        body(`Headline: ${a.adCopy.headline as string || ''}`),
        body(a.adCopy.primaryText as string || ''),
        body(`CTA: ${a.adCopy.cta as string || ''}`),
      )
    }
    children.push(divider())
  }

  // Funnel
  if (data.funnel) {
    const f = data.funnel as Record<string, unknown>
    children.push(heading('3. Funnel Blueprint'))

    if (f.leadMagnet) {
      const lm = f.leadMagnet as Record<string, string>
      children.push(
        heading('Lead Magnet', HeadingLevel.HEADING_2),
        body(`Title: ${lm.title}`),
        body(`Format: ${lm.format}`),
        body(lm.deliverable),
      )
    }

    if (f.crmStages) {
      children.push(heading('CRM Pipeline Stages', HeadingLevel.HEADING_2))
      for (const stage of f.crmStages as string[]) children.push(bullet(stage))
    }
    children.push(divider())
  }

  // Leads
  if (data.leads) {
    const l = data.leads as Record<string, unknown>
    children.push(heading('4. Lead Generation Plan'))

    if ((l.outboundStrategy as Record<string, unknown>)?.coldEmailSubject) {
      const ob = l.outboundStrategy as Record<string, string>
      children.push(
        heading('Cold Email', HeadingLevel.HEADING_2),
        body(`Subject: ${ob.coldEmailSubject}`),
        body(ob.coldEmailPreview || ''),
      )
    }

    if (l.qualificationRules) {
      children.push(heading('Qualification Rules', HeadingLevel.HEADING_2))
      for (const rule of l.qualificationRules as string[]) children.push(bullet(rule))
    }
  }

  const doc = new Document({
    sections: [{ children }],
    creator: 'Ooumph AI Marketing OS',
    title: `${data.brand.business_name} — AI Marketing Plan`,
  })

  return Buffer.from(await Packer.toBuffer(doc))
}
