/**
 * lib/tools/cloudinary-video.ts — Sprint 19A
 *
 * Cloudinary video transformation wrapper. Powers the prompt-driven editor
 * on /dashboard/video-gen: concat clips generated by Runway / Pika / Luma /
 * Sora / Kling / HeyGen, apply trim / fade / speed / overlay / subtitle /
 * audio-mix transformations, all via URL parameters — no ffmpeg, no
 * Remotion-render-host needed.
 *
 * Reads credentials via `getCredential()` (request-scoped) so workspace
 * BYOK keys flow through correctly per Sprint 18I.
 *
 * Note: Cloudinary's free plan covers up to ~25 GB delivery + 25 credits
 * worth of transformations per month. For high-volume production assembly
 * you'd move to a paid plan or to Shotstack (Sprint 19B).
 */
import crypto from 'crypto'
import { getCredential } from '@/lib/credential-context'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface CloudinaryVideoAsset {
  publicId: string
  url: string
  secureUrl: string
  format: string
  width?: number
  height?: number
  durationSec?: number
  bytes: number
  createdAt?: string
}

export type OverlayPosition =
  | 'top_left' | 'top' | 'top_right'
  | 'left' | 'center' | 'right'
  | 'bottom_left' | 'bottom' | 'bottom_right'

export interface ImageOverlay {
  type: 'image'
  publicId: string                // already-uploaded Cloudinary image
  position?: OverlayPosition
  widthPct?: number               // 0-100, % of base width
  opacityPct?: number             // 0-100
  startSec?: number               // when to show
  durationSec?: number            // how long
}

export interface TextOverlay {
  type: 'text'
  text: string
  fontFamily?: string             // 'Arial', 'Roboto', etc.
  fontSize?: number               // px
  color?: string                  // hex without '#'
  position?: OverlayPosition
  startSec?: number
  durationSec?: number
}

export type Overlay = ImageOverlay | TextOverlay

/**
 * Canonical edit spec. Claude parses prompts into this shape; the URL
 * builder translates each field to Cloudinary transform parameters.
 */
export interface VideoEditSpec {
  trim?: { startSec: number; durationSec: number }
  speedPct?: number               // 50 = half speed, 200 = double speed (range 50-200)
  fadeInMs?: number
  fadeOutMs?: number
  overlays?: Overlay[]
  voiceoverPublicId?: string      // Cloudinary public ID of audio file
  voiceoverVolumePct?: number     // 0-200 (100 = unchanged)
  bgmPublicId?: string
  bgmVolumePct?: number           // typically 10-30 when under voiceover
  subtitlesPublicId?: string      // Cloudinary public ID of SRT file
  crop?: { width: number; height: number; mode?: 'fill' | 'fit' | 'crop' | 'pad' }
  brightness?: number             // -100 to 100
  saturation?: number             // -100 to 100
  concatPublicIds?: string[]      // additional clips to splice after the base
  muteAudio?: boolean
  loudnessNormalize?: boolean
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function buildSignature(params: Record<string, string | number>, apiSecret: string): string {
  const sorted = Object.keys(params).sort().map(k => `${k}=${params[k]}`).join('&')
  return crypto.createHash('sha1').update(sorted + apiSecret).digest('hex')
}

function clamp(n: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, n))
}

function gravityFor(p: OverlayPosition | undefined): string {
  switch (p) {
    case 'top_left':     return 'north_west'
    case 'top':          return 'north'
    case 'top_right':    return 'north_east'
    case 'left':         return 'west'
    case 'right':        return 'east'
    case 'bottom_left':  return 'south_west'
    case 'bottom':       return 'south'
    case 'bottom_right': return 'south_east'
    case 'center':
    default:             return 'center'
  }
}

function escapeText(t: string): string {
  // Cloudinary's URL-encoded overlay text: replace , and / and special chars
  return encodeURIComponent(t).replace(/%2C/g, '%252C').replace(/%2F/g, '%252F')
}

// ─── Upload a remote MP4 to Cloudinary ────────────────────────────────────────

export async function uploadVideoUrl(
  videoUrl: string,
  folder?: string,
): Promise<CloudinaryVideoAsset | null> {
  const cloudName = getCredential('CLOUDINARY_CLOUD_NAME')
  const apiKey = getCredential('CLOUDINARY_API_KEY')
  const apiSecret = getCredential('CLOUDINARY_API_SECRET')
  if (!cloudName || !apiKey || !apiSecret) return null

  const timestamp = Math.floor(Date.now() / 1000)
  const params: Record<string, string | number> = {
    timestamp,
    resource_type: 'video',
  }
  if (folder) params.folder = folder
  // resource_type is NOT included in signature per Cloudinary spec
  const sigParams = { ...params }
  delete sigParams.resource_type
  const signature = buildSignature(sigParams, apiSecret)

  const form = new FormData()
  form.append('file', videoUrl)
  if (folder) form.append('folder', folder)
  form.append('timestamp', String(timestamp))
  form.append('api_key', apiKey)
  form.append('signature', signature)
  form.append('resource_type', 'video')

  try {
    const res = await fetch(
      `https://api.cloudinary.com/v1_1/${cloudName}/video/upload`,
      { method: 'POST', body: form },
    )
    if (!res.ok) {
      console.error('[cloudinary-video.upload] HTTP', res.status, await res.text().catch(() => ''))
      return null
    }
    const data = await res.json() as Record<string, unknown>
    return {
      publicId: data.public_id as string,
      url: data.url as string,
      secureUrl: data.secure_url as string,
      format: data.format as string,
      width: data.width as number | undefined,
      height: data.height as number | undefined,
      durationSec: data.duration as number | undefined,
      bytes: data.bytes as number,
      createdAt: data.created_at as string | undefined,
    }
  } catch (err) {
    console.error('[cloudinary-video.upload]', err)
    return null
  }
}

// ─── Translate VideoEditSpec → Cloudinary transformation segments ────────────

/**
 * Produces an array of `/`-joined transformation segments that can be
 * inserted into a Cloudinary video URL. Returns [] if spec is empty.
 *
 * The order matters: trim first (operates on source), then concat, then
 * crop, then overlays (image/text), then audio mix, then color, then
 * speed, then fade. This mirrors Cloudinary's documented evaluation order.
 */
export function specToTransformations(spec: VideoEditSpec): string[] {
  const segs: string[] = []

  // 1. Trim
  if (spec.trim) {
    const so = Math.max(0, spec.trim.startSec)
    const du = Math.max(0.1, spec.trim.durationSec)
    segs.push(`so_${so},du_${du}`)
  }

  // 2. Concatenate additional clips (each splice is its own transformation)
  if (spec.concatPublicIds && spec.concatPublicIds.length > 0) {
    for (const id of spec.concatPublicIds) {
      // l_video: prefix + public ID, fl_splice to join, then fl_layer_apply.
      // Cloudinary uses : as separator inside layer params, : in IDs is rare.
      const safe = id.replace(/\//g, ':')
      segs.push(`l_video:${safe},fl_splice`)
      segs.push('fl_layer_apply')
    }
  }

  // 3. Crop / resize
  if (spec.crop) {
    const mode = spec.crop.mode || 'fill'
    segs.push(`w_${spec.crop.width},h_${spec.crop.height},c_${mode}`)
  }

  // 4. Overlays (image + text)
  if (spec.overlays && spec.overlays.length > 0) {
    for (const ov of spec.overlays) {
      const parts: string[] = []
      if (ov.type === 'image') {
        parts.push(`l_${ov.publicId.replace(/\//g, ':')}`)
        if (ov.widthPct) parts.push(`w_${clamp(ov.widthPct, 1, 100) / 100}`)
        if (ov.opacityPct !== undefined) parts.push(`o_${clamp(ov.opacityPct, 0, 100)}`)
      } else {
        const font = ov.fontFamily || 'Arial'
        const size = ov.fontSize || 48
        parts.push(`l_text:${font}_${size}:${escapeText(ov.text)}`)
        if (ov.color) parts.push(`co_rgb:${ov.color}`)
      }
      parts.push(`g_${gravityFor(ov.position)}`)
      if (ov.startSec !== undefined) parts.push(`so_${ov.startSec}`)
      if (ov.durationSec !== undefined) parts.push(`du_${ov.durationSec}`)
      segs.push(parts.join(','))
      segs.push('fl_layer_apply')
    }
  }

  // 5. Subtitles overlay (SRT)
  if (spec.subtitlesPublicId) {
    const safe = spec.subtitlesPublicId.replace(/\//g, ':')
    segs.push(`l_subtitles:${safe}`)
    segs.push('fl_layer_apply')
  }

  // 6. Voiceover (replaces or layers on top of source audio)
  if (spec.voiceoverPublicId) {
    const safe = spec.voiceoverPublicId.replace(/\//g, ':')
    const volSeg = spec.voiceoverVolumePct !== undefined
      ? `,e_volume:${clamp(spec.voiceoverVolumePct - 100, -100, 100)}`
      : ''
    segs.push(`l_video:${safe}${volSeg},fl_layer_apply`)
  }

  // 7. BGM (under voiceover — typically -12 to -24 dB which we express as -75 to -90 volume pct)
  if (spec.bgmPublicId) {
    const safe = spec.bgmPublicId.replace(/\//g, ':')
    const vol = spec.bgmVolumePct !== undefined ? clamp(spec.bgmVolumePct, 0, 100) - 100 : -75
    segs.push(`l_video:${safe},e_volume:${vol},fl_layer_apply`)
  }

  // 8. Mute audio (if requested AFTER overlays — keeps voiceover/bgm we just added)
  if (spec.muteAudio) {
    segs.push('e_volume:mute')
  }

  // 9. Loudness normalize (Cloudinary's auto-leveler)
  if (spec.loudnessNormalize) {
    segs.push('e_volume:auto')
  }

  // 10. Color
  if (spec.brightness !== undefined) {
    segs.push(`e_brightness:${clamp(spec.brightness, -100, 100)}`)
  }
  if (spec.saturation !== undefined) {
    segs.push(`e_saturation:${clamp(spec.saturation, -100, 100)}`)
  }

  // 11. Speed
  if (spec.speedPct !== undefined && spec.speedPct !== 100) {
    // Cloudinary's e_accelerate is in percent (100 = unchanged, 200 = 2x, 50 = 0.5x)
    segs.push(`e_accelerate:${clamp(spec.speedPct, 50, 400)}`)
  }

  // 12. Fade
  if (spec.fadeInMs && spec.fadeInMs > 0) {
    segs.push(`e_fade:${clamp(spec.fadeInMs, 100, 10000)}`)
  }
  if (spec.fadeOutMs && spec.fadeOutMs > 0) {
    segs.push(`e_fade:-${clamp(spec.fadeOutMs, 100, 10000)}`)
  }

  return segs
}

/**
 * Build the final Cloudinary video URL for a given source clip + edit spec.
 * Returns null when Cloudinary isn't configured.
 */
export function buildEditedVideoUrl(basePublicId: string, spec: VideoEditSpec): string | null {
  const cloudName = getCredential('CLOUDINARY_CLOUD_NAME')
  if (!cloudName) return null
  const segs = specToTransformations(spec)
  const transforms = segs.length > 0 ? segs.join('/') + '/' : ''
  return `https://res.cloudinary.com/${cloudName}/video/upload/${transforms}${basePublicId}.mp4`
}

export function isCloudinaryVideoAvailable(): boolean {
  return Boolean(
    getCredential('CLOUDINARY_CLOUD_NAME') &&
    getCredential('CLOUDINARY_API_KEY') &&
    getCredential('CLOUDINARY_API_SECRET'),
  )
}
